"""Canonical image tensor contract shared by training and deployment."""

IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224
IMAGE_CHANNELS = 3
INPUT_CONTRACT_VERSION = "rgb-224-square-v1"

TRAINING_INPUT_SHAPE = (IMAGE_CHANNELS, IMAGE_HEIGHT, IMAGE_WIDTH)  # NCHW tail
DEPLOYMENT_INPUT_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS)  # NHWC tail
IMAGE_SIZE_LABEL = f"{IMAGE_HEIGHT}x{IMAGE_WIDTH}"
